language: php
php:
  - 5.5
  - 5.6

cache: false

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=3.3
    - DB=MYSQL CORE_RELEASE=3

before_script:
  - phpenv rehash
  - git clone -b prefer-source git://github.com/kinglozzer/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --prefer-source
  - cd ~/builds/ss

script:
  - phpunit oauth-login/tests/
