Bigfork\SilverStripeOAuth\Client\Control\Controller:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\ControllerExtension
Injector:
  MemberMapperFactory:
    class: Bigfork\SilverStripeOAuth\Client\Factory\MemberMapperFactory
Member:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\MemberExtension
OAuthAccessToken:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\OAuthAccessTokenExtension
