Bigfork\SilverStripeOAuth\Client\Control\Controller:
  token_handlers:
    loginhandler:
      priority: 1
      context: login
      class: Bigfork\SilverStripeOAuth\Client\Handler\LoginTokenHandler
Injector:
  MemberMapperFactory:
    class: Bigfork\SilverStripeOAuth\Client\Factory\MemberMapperFactory
Member:
  extensions:
    - Bigfork\SilverStripeOAuth\Client\Extension\MemberExtension
